
services:
  postgres:
    image: postgres:15
    container_name: temporal-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  temporal:
    image: temporalio/auto-setup:1.29.2
    container_name: temporal
    depends_on:
      - postgres
    ports:
      - "7233:7233"
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PWD: admin
      POSTGRES_SEEDS: postgres
      DBNAME: temporal
      VISIBILITY_DBNAME: temporal_visibility
    volumes:
      - temporal_data:/etc/temporal
    restart: unless-stopped

  temporal-ui:
    image: temporalio/ui:2.44.1
    container_name: temporal-ui
    depends_on:
      - temporal
    ports:
      - "8088:8080"
    environment:
      # TEMPORAL_GRPC_ENDPOINT: temporal:7233
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_PERMIT_WRITE_API: "true"

volumes:
  postgres_data:
  temporal_data: